# -*- coding: utf-8 -*-
"""Untitled200.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dPspAA2fZGhhH_-j0_j8muSZ5P4WPDuu
"""

import streamlit as st
import pyttsx3
import google.cloud.speech

# Initialize the text-to-speech engine
engine = pyttsx3.init()

# Set the voice
engine.setProperty('voice', 'en-US')

# Define the function that converts speech to Arabic sign language
def convert_speech_to_asl(text):
    # Create a speech client
    speech_client = google.cloud.speech.SpeechClient()

    # Set the encoding
    encoding = 'LINEAR16'

    # Set the sample rate
    sample_rate = 16000

    # Create a request
    request = google.cloud.speech.types.StreamingRecognizeRequest()

    # Add the audio content to the request
    request.audio_content = st.audio_input('Enter your speech:')

    # Recognize the speech
    responses = speech_client.streaming_recognize(request)

    # Convert the speech to text
    for response in responses:
        for alternative in response.alternatives:
            text = alternative.transcript

    # Generate the sign language video
    arabic_text = asl.translate(text)
    video = asl.generate_video(arabic_text)

    # Return the video
    return video

# Create the Streamlit app
st.title('Speech to Arabic Sign Language Converter')

# Get the user's input
text = st.text_input('Enter your speech:')

# Convert the user's input to Arabic sign language
video = convert_speech_to_asl(text)

# Display the sign language video
st.video(video)